### ISSUE TITLE
Published on the supermarket

### ISSUE THREAD

**Issue by tas50** [pantheon-cookbooks/dnf#13]
Any chance this will be up on the supermarket soon?

**Comment by fujin** [comment]
sure thing, we will push this week.

**Comment by fujin** [comment]
we took a holiday and didn't do this. try to do this week. :)

**Comment by fujin** [comment]
@joemiller any preference for who uploads this to le supermarche

**Comment by tas50** [comment]
Everyone deserves vacations.  No worries

**Comment by fujin** [comment]
@tas50 <3

**Comment by fujin** [comment]
@tas50 :heart:

**Comment by joemiller** [comment]
done: https://supermarket.chef.io/cookbooks/dnf

**Comment by thommay** [comment]
nice one! <3 thank you all

**Comment by fujin** [comment]
Awesome thanks @joemiller :D
